# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jre-slim

# Set the working directory to /app
WORKDIR /

# Expose port 8080 for the Spring Boot application
EXPOSE 8080

# Specify the command to run your Spring Boot application
CMD ["java", "-jar", "employeemanagmentbackend-0.0.1-SNAPSHOT.jar"]
